# should all the files be merged into one? That is how it looks for examples
path:  /mnt/home/robsonj3/merged_k40.parquet # /mnt/gs21/scratch/robsonj3/k40sim/parquet/K40PulseMap/*.parquet #was this: $GRAPHNET/data/examples/sqlite/prometheus/prometheus-events.db
graph_definition:
  arguments:
    columns: [0, 1, 2]
    detector:
      arguments: {}
      class_name: PONE # was this: Prometheus
    dtype: torch.float32
    nb_nearest_neighbours: 8
    node_definition:
      arguments: {}
      class_name: NodesAsPulses
    input_feature_names: [dom_x, dom_y, dom_z, time, charge] # copied the features from below
  class_name: KNNGraph
pulsemaps:
  - total
features:  # got features from here: /mnt/home/robsonj3/graphnet/src/graphnet/data/constants.py
  - dom_x
  - dom_y
  - dom_z
  - time
  - charge
truth:  # got truth from here: /mnt/home/robsonj3/graphnet/src/graphnet/data/constants.py
  - zenith
  - azimuth
  - energy
  - dummy_pid
index_column: event_no
truth_table: mc_truth
seed: 21
selection:  # selection format is incorrect for parquet??
  test: event_no % 5 == 0
  validation: event_no % 5 == 1
  train: event_no % 5 > 1